version: '3.8'

services:
  
  postgres-users:
    container_name: my_postgres_container_for_Users
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usersDB
    ports:
      - "5433:5432"
    volumes:
      - postgres-users-data:/var/lib/postgresql/data
    networks:
      - microservices-net

  

  # ---------------- pgAdmin ----------------
  pgadmin:
    container_name: my_pgadmin2
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-users

    networks:
      - microservices-net



# ---------------- Volumes ----------------
volumes:
  postgres-users-data:

# ---------------- Network ----------------
networks:
  microservices-net:
    driver: bridge
